In [64]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [65]:
retails_Sales = pd.read_csv(r'retail_sales_dataset.csv')

In [66]:
retails_Sales.head(5)

,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,region,category,sub_category,product_name,sales,quantity,discount,profit
0,ORD-2023-101194,24/01/2024,25/01/2024,First Class,CUST-1115,Customer_1158,Consumer,India,Kochi,South,Furniture,Furnishings,Furnishings_115,8234.93,11,0.00,2385.03
1,ORD-2023-101574,17/12/2024,18/12/2024,Second Class,CUST-1203,Customer_1327,NaN,India,Mumbai,WEST,Office Supplies,Supplies,Supplies_235,9675.40,9,0.40,1419.75
2,ORD-2023-100007,2023-06-17,21/06/2023,Second Class,CUST-1350,Customer_1166,Consumer,India,Chandigarh,North,Technology,Machines,Machines_118,9916.03,7,0.15,3774.85
3,ORD-2023-100004,06/04/2025,07/04/2025,Standard Class,CUST-1498,Customer_1472,Corporate,India,Bhubaneswar,East,Technology,Accessories,Accessories_41,904.25,12,0.40,69.48
4,ORD-2023-100925,28/03/2023,29/03/2023,Second Class,CUST-1219,Customer_1271,Corporate,India,Lucknow,North,Furniture,Bookcases,Bookcases_93,17749.80,10,0.00,4862.85

In [67]:
retails_Sales.isnull().sum()

order_id          0
order_date        0
ship_date         0
ship_mode        94
customer_id       0
customer_name     0
segment          93
country           0
city             93
region           90
category          0
sub_category      0
product_name      0
sales             0
quantity          0
discount         90
profit           93
dtype: int64

In [68]:
retails_Sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3060 entries, 0 to 3059
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       3060 non-null   object
 1   order_date     3060 non-null   object
 2   ship_date      3060 non-null   object
 3   ship_mode      2966 non-null   object
 4   customer_id    3060 non-null   object
 5   customer_name  3060 non-null   object
 6   segment        2967 non-null   object
 7   country        3060 non-null   object
 8   city           2967 non-null   object
 9   region         2970 non-null   object
 10  category       3060 non-null   object
 11  sub_category   3060 non-null   object
 12  product_name   3060 non-null   object
 13  sales          3060 non-null   float64
 14  quantity       3060 non-null   int64
 15  discount       2970 non-null   float64
 16  profit         2967 non-null   float64
dtypes: float64(3), int64(1), object(13)
memory usage: 406.5+ KB

In [86]:
retails_Sales.describe()

,order_date,ship_date,sales,quantity,discount,profit
count,3007,3007,3007.000000,3007.000000,3007.000000,3007.000000
mean,2024-03-29 20:06:47.050215936,2024-03-25 13:38:24.622546944,5993.303775,7.465248,0.182893,1680.774532
min,2023-01-01 00:00:00,2023-01-03 00:00:00,5.650000,1.000000,0.000000,0.120000
25%,2023-08-06 12:00:00,2023-08-09 12:00:00,1799.355000,4.000000,0.000000,394.435000
50%,2024-03-21 00:00:00,2024-03-22 00:00:00,4426.740000,8.000000,0.150000,1075.790000
75%,2024-11-12 12:00:00,2024-11-10 00:00:00,8820.650000,11.000000,0.300000,2324.545000
max,2025-12-06 00:00:00,2025-06-26 00:00:00,27669.180000,14.000000,0.500000,12506.820000
std,NaN,NaN,5337.763109,4.036350,0.173801,1797.598569

In [69]:
retails_Sales.shape

(3060, 17)

In [119]:
retails_Sales.duplicated().sum()

np.int64(0)

In [149]:
retails_Sales = retails_Sales.reset_index(drop=True)

In [150]:
retails_Sales.isnull().sum()

order_id         0
order_date       0
ship_date        0
ship_mode        0
customer_id      0
customer_name    0
segment          0
country          0
city             0
region           0
category         0
sub_category     0
product_name     0
sales            0
quantity         0
discount         0
profit           0
dtype: int64

In [151]:
retails_Sales['ship_mode'] = retails_Sales['ship_mode'].fillna(retails_Sales['ship_mode'].mode()[0])

In [152]:
retails_Sales['ship_mode'] = retails_Sales['ship_mode'].str.strip().str.title()

In [153]:
retails_Sales['segment'] = retails_Sales['segment'].fillna(retails_Sales['segment'].mode()[0])

In [154]:
retails_Sales['segment'] = retails_Sales['segment'].str.strip().str.title()

In [155]:
retails_Sales['city'] = retails_Sales['city'].fillna('unkown')

In [157]:
retails_Sales['region'] = retails_Sales['region'].fillna(retails_Sales['region'].mode()[0])

In [158]:
retails_Sales['region'] = retails_Sales['region'].str.title()

In [159]:
retails_Sales['discount'] = retails_Sales['discount'].fillna(retails_Sales['discount'].mean())

In [160]:
retails_Sales['profit'] = retails_Sales['profit'].fillna(retails_Sales['profit'].mean())

In [161]:
retails_Sales['order_date'] = pd.to_datetime(retails_Sales['order_date'],format='mixed')

In [162]:
retails_Sales['ship_date'] = pd.to_datetime(retails_Sales['ship_date'])

In [170]:
retails_Sales.to_csv('Retails_Sales.csv',index=False)