In [37]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [18]:
data = pd.read_csv(r'Retails_Sales.csv')

In [19]:
data.head(2)

,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,region,category,sub_category,product_name,sales,quantity,discount,profit
0,ORD-2023-101194,2024-01-24,2024-01-25,First Class,CUST-1115,Customer_1158,Consumer,India,Kochi,South,Furniture,Furnishings,Furnishings_115,8234.93,11,0.0,2385.03
1,ORD-2023-101574,2024-12-17,2024-12-18,Second Class,CUST-1203,Customer_1327,Home Office,India,Mumbai,West,Office Supplies,Supplies,Supplies_235,9675.40,9,0.4,1419.75

In [20]:
data.describe()

              sales     quantity     discount        profit
count   3000.000000  3000.000000  3000.000000   3000.000000
mean    5998.181737     7.461333     0.183053   1682.808179
std     5340.160581     4.033435     0.173868   1799.038702
min        5.650000     1.000000     0.000000      0.120000
25%     1800.067500     4.000000     0.000000    394.290000
50%     4427.170000     8.000000     0.150000   1079.205000
75%     8829.340000    11.000000     0.300000   2330.632500
max    27669.180000    14.000000     0.500000  12506.820000

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       3000 non-null   object
 1   order_date     3000 non-null   object
 2   ship_date      3000 non-null   object
 3   ship_mode      3000 non-null   object
 4   customer_id    3000 non-null   object
 5   customer_name  3000 non-null   object
 6   segment        3000 non-null   object
 7   country        3000 non-null   object
 8   city           3000 non-null   object
 9   region         3000 non-null   object
 10  category       3000 non-null   object
 11  sub_category   3000 non-null   object
 12  product_name   3000 non-null   object
 13  sales          3000 non-null   float64
 14  quantity       3000 non-null   int64
 15  discount       3000 non-null   float64
 16  profit         3000 non-null   float64
dtypes: float64(3), int64(1), object(13)
memory usage: 398.6+ KB

In [22]:
x = data[['sales', 'quantity', 'discount', 'region', 'category', 'segment', 'ship_mode']]

In [23]:
y = data['profit']

In [24]:
x = pd.get_dummies(x,columns=['region','category','segment','ship_mode'],drop_first=True)

In [25]:
from sklearn.model_selection import train_test_split

In [77]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [78]:
from sklearn.linear_model import LinearRegression

In [90]:
from sklearn.metrics import r2_score , confusion_matrix , mean_squared_error

In [80]:
from sklearn.preprocessing import StandardScaler

In [81]:
scaler = StandardScaler()

In [82]:
x_train_scled = scaler.fit_transform(x_train)

In [83]:
x_test_scled = scaler.transform(x_test)

In [84]:
lr_model = LinearRegression()

In [85]:
lr_model.fit(x_train_scled,y_train)

LinearRegression()

In [86]:
ypred = lr_model.predict(x_test_scled)

In [87]:
r2_score(ypred,y_test)

0.712682103790417

In [88]:
np.sqrt(mean_squared_error(ypred,y_test))

np.float64(828.6804808761937)

In [94]:
from sklearn.ensemble import RandomForestRegressor

In [95]:
rf_model = RandomForestRegressor()

In [97]:
rf_model.fit(x_train_scled,y_train)

RandomForestRegressor()

In [98]:
rpred = rf_model.predict(x_test_scled)

In [101]:
print("Random Forest R² Score:", r2_score(y_test, rpred))

Random Forest R² Score: 0.7474732813759382

In [103]:
print("Random Forest RMSE:", np.sqrt(mean_squared_error(y_test, rpred)))

Random Forest RMSE: 847.3651781934425